import '../../presentation/auth/widgets/phone_input_field.dart';

final List<CountryCode> countries = [
  const CountryCode(
    code: 'IN',
    name: 'India',
    dialCode: '+91',
    flag: '🇮🇳',
    minLength: 10,
    maxLength: 10,
  ),
  const CountryCode(
    code: 'US',
    name: 'United States',
    dialCode: '+1',
    flag: '🇺🇸',
    minLength: 10,
    maxLength: 10,
  ),
  const CountryCode(
    code: 'GB',
    name: 'United Kingdom',
    dialCode: '+44',
    flag: '🇬🇧',
    minLength: 10,
    maxLength: 10,
  ),
  const CountryCode(
    code: 'CA',
    name: 'Canada',
    dialCode: '+1',
    flag: '🇨🇦',
    minLength: 10,
    maxLength: 10,
  ),
  const CountryCode(
    code: 'AU',
    name: 'Australia',
    dialCode: '+61',
    flag: '🇦🇺',
    minLength: 9,
    maxLength: 9,
  ),
  const CountryCode(
    code: 'AE',
    name: 'United Arab Emirates',
    dialCode: '+971',
    flag: '🇦🇪',
    minLength: 9,
    maxLength: 9,
  ),
  const CountryCode(
    code: 'SG',
    name: 'Singapore',
    dialCode: '+65',
    flag: '🇸🇬',
    minLength: 8,
    maxLength: 8,
  ),
  const CountryCode(
    code: 'MY',
    name: 'Malaysia',
    dialCode: '+60',
    flag: '🇲🇾',
    minLength: 9,
    maxLength: 10,
  ),
  const CountryCode(
    code: 'PK',
    name: 'Pakistan',
    dialCode: '+92',
    flag: '🇵🇰',
    minLength: 10,
    maxLength: 10,
  ),
  const CountryCode(
    code: 'BD',
    name: 'Bangladesh',
    dialCode: '+880',
    flag: '🇧🇩',
    minLength: 10,
    maxLength: 10,
  ),
  const CountryCode(
    code: 'LK',
    name: 'Sri Lanka',
    dialCode: '+94',
    flag: '🇱🇰',
    minLength: 9,
    maxLength: 9,
  ),
  const CountryCode(
    code: 'NP',
    name: 'Nepal',
    dialCode: '+977',
    flag: '🇳🇵',
    minLength: 10,
    maxLength: 10,
  ),
  const CountryCode(
    code: 'JP',
    name: 'Japan',
    dialCode: '+81',
    flag: '🇯🇵',
    minLength: 10,
    maxLength: 10,
  ),
  const CountryCode(
    code: 'CN',
    name: 'China',
    dialCode: '+86',
    flag: '🇨🇳',
    minLength: 11,
    maxLength: 11,
  ),
  const CountryCode(
    code: 'KR',
    name: 'South Korea',
    dialCode: '+82',
    flag: '🇰🇷',
    minLength: 10,
    maxLength: 10,
  ),
  const CountryCode(
    code: 'DE',
    name: 'Germany',
    dialCode: '+49',
    flag: '🇩🇪',
    minLength: 10,
    maxLength: 11,
  ),
  const CountryCode(
    code: 'FR',
    name: 'France',
    dialCode: '+33',
    flag: '🇫🇷',
    minLength: 9,
    maxLength: 9,
  ),
  const CountryCode(
    code: 'IT',
    name: 'Italy',
    dialCode: '+39',
    flag: '🇮🇹',
    minLength: 10,
    maxLength: 10,
  ),
  const CountryCode(
    code: 'ES',
    name: 'Spain',
    dialCode: '+34',
    flag: '🇪🇸',
    minLength: 9,
    maxLength: 9,
  ),
  const CountryCode(
    code: 'BR',
    name: 'Brazil',
    dialCode: '+55',
    flag: '🇧🇷',
    minLength: 10,
    maxLength: 11,
  ),
  const CountryCode(
    code: 'MX',
    name: 'Mexico',
    dialCode: '+52',
    flag: '🇲🇽',
    minLength: 10,
    maxLength: 10,
  ),
  const CountryCode(
    code: 'ZA',
    name: 'South Africa',
    dialCode: '+27',
    flag: '🇿🇦',
    minLength: 9,
    maxLength: 9,
  ),
  const CountryCode(
    code: 'NG',
    name: 'Nigeria',
    dialCode: '+234',
    flag: '🇳🇬',
    minLength: 10,
    maxLength: 10,
  ),
  const CountryCode(
    code: 'EG',
    name: 'Egypt',
    dialCode: '+20',
    flag: '🇪🇬',
    minLength: 10,
    maxLength: 10,
  ),
  const CountryCode(
    code: 'SA',
    name: 'Saudi Arabia',
    dialCode: '+966',
    flag: '🇸🇦',
    minLength: 9,
    maxLength: 9,
  ),
];