// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOjSBARWhC6Ecys5KO9O82kOr7zj_v5NE',
    appId: '1:634611303787:web:fa871c8a0cdf5d0038b82e',
    messagingSenderId: '634611303787',
    projectId: 'calorix-5694a',
    authDomain: 'calorix-5694a.firebaseapp.com',
    storageBucket: 'calorix-5694a.firebasestorage.app',
    measurementId: 'G-1MQVMYMLJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZzSgsN5dh5CE61JOPwUjpX5C8FRQuuW0',
    appId: '1:634611303787:android:ce1d8020b43f99f738b82e',
    messagingSenderId: '634611303787',
    projectId: 'calorix-5694a',
    storageBucket: 'calorix-5694a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPv2ssAqUhzzMN2-Rq9Cyvm-_5KYv77wg',
    appId: '1:634611303787:ios:7f9f2b161be8b51238b82e',
    messagingSenderId: '634611303787',
    projectId: 'calorix-5694a',
    storageBucket: 'calorix-5694a.firebasestorage.app',
    iosBundleId: 'com.calorix.calorixApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPv2ssAqUhzzMN2-Rq9Cyvm-_5KYv77wg',
    appId: '1:634611303787:ios:7f9f2b161be8b51238b82e',
    messagingSenderId: '634611303787',
    projectId: 'calorix-5694a',
    storageBucket: 'calorix-5694a.firebasestorage.app',
    iosBundleId: 'com.calorix.calorixApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOjSBARWhC6Ecys5KO9O82kOr7zj_v5NE',
    appId: '1:634611303787:web:263d8734be6b15fd38b82e',
    messagingSenderId: '634611303787',
    projectId: 'calorix-5694a',
    authDomain: 'calorix-5694a.firebaseapp.com',
    storageBucket: 'calorix-5694a.firebasestorage.app',
    measurementId: 'G-9FENL5F3QQ',
  );
}
